[project]
name = "mcp-tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.9.3",
    "edge-tts==7.0.2",
    "nest-asyncio==1.6.0",
]
